import 'package:conway/conway.dart' as foo;
import 'package:test/test.dart';

void main() {
  const _halfArrow = '''
..#..
..##.
..###
..#..
..#..
..#..
''';
  const _identity = '''
#.....
.#....
..#...
...#..
....#.
.....#
''';

  test('construction from string', () {
    expect(
        foo.SimpleWorld.fromString(_halfArrow).toString(), equals(_halfArrow));
  });

  test('identity', () {
    expect(
        SimpleWorld.identity(6).toString(), equals(_identity));
  });

  test('paste', () {
    var w = SimpleWorld.identity(12);
    w = paste(w, 0, 0, SimpleWorld.fromString(_halfArrow));
    expect(w.toString(), equals('''
..#.........
..##........
..###.......
..#.........
..#.........
..#..#......
......#.....
.......#....
........#...
.........#..
..........#.
...........#
'''));
    w = SimpleWorld.identity(12);
    foo.paste(w, 0, 3, SimpleWorld.fromString(_halfArrow));
    expect(w.toString(), equals('''
#....#......
.#...##.....
..#..###....
.....#......
.....#......
.....#......
......#.....
.......#....
........#...
.........#..
..........#.
...........#
'''));
    w = SimpleWorld.identity(12);
    paste(4, 4, SimpleWorld.fromString(_halfArrow));
    expect(w.toString(), equals('''
#...........
.#..........
..#.........
...#........
......#.....
......##....
......###...
......#.....
......#.....
......#..#..
..........#.
...........#
'''));
    w = SimpleWorld.identity(12);
    w.paste(12, 12, SimpleWorld.fromString(_halfArrow));
    expect(w.toString(), equals('''
..#.........
..##........
..###.......
..#.........
..#.........
..#..#......
......#.....
.......#....
........#...
.........#..
..........#.
...........#
'''));
    w = SimpleWorld.identity(12);
    w = w.expandToPaste(12, 12, SimpleWorld.fromString(_halfArrow));
    expect(w.toString(), equals('''
#................
.#...............
..#..............
...#.............
....#............
.....#...........
......#..........
.......#.........
........#........
.........#.......
..........#......
...........#.....
..............#..
..............##.
..............###
..............#..
..............#..
..............#..
'''));
  });

  test('counterClockwise90', () {
    var w = SimpleWorld.fromString(_halfArrow);
    w = w.counterClockwise90();
    expect(w.toString(), equals('''
..#...
.##...
######
......
......
'''));
    expect(
        w
            .counterClockwise90()
            .counterClockwise90()
            .counterClockwise90()
            .toString(),
        equals(_halfArrow));
  });

  test('clockwise90', () {
    var w = SimpleWorld.fromString(_halfArrow);
    w = w.clockwise90();
    expect(w.toString(), equals('''
......
......
######
...##.
...#..
'''));
    expect(w.clockwise90().clockwise90().clockwise90().toString(),
        equals(_halfArrow));
  });

  test('transpose', () {
    var w = SimpleWorld.fromString(_halfArrow);
    w = w.transpose();
    expect(w.toString(), equals('''
......
......
######
.##...
..#...
'''));
    expect(SimpleWorld.fromString(_identity).transpose().toString(),
        equals(_identity));
    w = SimpleWorld.fromString('''
...#...
..#.#..
.#.#.#.
...#...
...#...
...#...
''');
    w = w.transpose();
    expect(w.toString(), equals('''
......
..#...
.#....
#.####
.#....
..#...
......
'''));
  });

  test('leftPadded', () {
    var w = SimpleWorld.fromString(_halfArrow).padLeft(2);
    expect(w.toString(), equals('''
....#..
....##.
....###
....#..
....#..
....#..
'''));
  });

  test('rightPadded', () {
    var w = SimpleWorld.fromString(_halfArrow).padRight(2);
    expect(w.toString(), equals('''
..#....
..##...
..###..
..#....
..#....
..#....
'''));
  });

  test('topPadded', () {
    var w = SimpleWorld.fromString(_halfArrow).padTop(2);
    expect(w.toString(), equals('''
.....
.....
..#..
..##.
..###
..#..
..#..
..#..
'''));
  });

  test('bottomPadded', () {
    var w = SimpleWorld.fromString(_halfArrow).padBottom(2);
    expect(w.toString(), equals('''
..#..
..##.
..###
..#..
..#..
..#..
.....
.....
'''));
  });

  test('append', () {
    var w = SimpleWorld.fromString(_halfArrow);
    w = w.appendRight(w).appendRight(w).appendRight(w);
    expect(w.toString(), equals('''
..#....#....#....#..
..##...##...##...##.
..###..###..###..###
..#....#....#....#..
..#....#....#....#..
..#....#....#....#..
'''));
    expect(w.appendBottom(w).toString(), equals('''
..#....#....#....#..
..##...##...##...##.
..###..###..###..###
..#....#....#....#..
..#....#....#....#..
..#....#....#....#..
..#....#....#....#..
..##...##...##...##.
..###..###..###..###
..#....#....#....#..
..#....#....#....#..
..#....#....#....#..
'''));
  });

  test('irregularAppendRight', () {
    var w = SimpleWorld.fromString(_halfArrow);
    w = w.appendRight(w.padTop(3));
    expect(w.toString(), equals('''
..#.......
..##......
..###.....
..#....#..
..#....##.
..#....###
.......#..
.......#..
.......#..
'''));
  });

  test('irregularAppendBottom', () {
    var w = SimpleWorld.fromString(_halfArrow);
    w = w.appendRight(w).appendRight(w);
    w = w.appendBottom(w.padLeft(3));
    expect(w.toString(), equals('''
..#....#....#.....
..##...##...##....
..###..###..###...
..#....#....#.....
..#....#....#.....
..#....#....#.....
.....#....#....#..
.....##...##...##.
.....###..###..###
.....#....#....#..
.....#....#....#..
.....#....#....#..
'''));
  });

  test('bigX', () {
    var ident = SimpleWorld.fromString(_identity);
    var v = ident.appendRight(ident.clockwise90());
    var x = v.appendBottom(v.clockwise90().clockwise90());
    expect(x.toString(), equals('''
#..........#
.#........#.
..#......#..
...#....#...
....#..#....
.....##.....
.....##.....
....#..#....
...#....#...
..#......#..
.#........#.
#..........#
'''));
  });

  test('mixItUp1', () {
    var r1 = SimpleWorld.fromString(_halfArrow).padLeft(2).padTop(2).padBottom(3).padRight(10);
    var r2 = r1.clockwise90().clockwise90();
    var w = r1.appendBottom(r2);
    expect(w.toString(), equals('''
.................
.................
....#............
....##...........
....###..........
....#............
....#............
....#............
.................
.................
.................
.................
.................
.................
............#....
............#....
............#....
..........###....
...........##....
............#....
.................
.................
'''));
  });

    test('mixItUp2', () {
      var w = SimpleWorld.fromString(_halfArrow).padRight(2);
      var w1 = w.appendRight(w.clockwise90());
      var w2 = w.counterClockwise90().appendRight(w);
      w = w1.appendBottom(w2);
      expect(w.toString(), equals('''
..#..........
..##.........
..###..######
..#.......##.
..#.......#..
..#..........
.............
........#....
........##...
..#.....###..
.##.....#....
######..#....
........#....
.............
'''));
  });
}
